### ISSUE TITLE
`fastgmad publish` errors after "preparing config" (Steam error: "a file was not found")

### ISSUE THREAD

**Issue by chev2** [WilliamVenner/fastgmad#1]
Here is my console log:
```
└─▪ >> fastgmad publish -addon auto_flashlight.gma -icon images/icon_auto_flashlight.jpg
fastgmad v0.1.1 by Billy
https://github.com/WilliamVenner/fastgmad
Prefer to use a GUI? Check out https://github.com/WilliamVenner/gmpublisher

[+16.22µs] Checking icon...
[+42.372µs] Initializing Steam...
[S_API] SteamAPI_Init(): Loaded '/home/cpcl/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 4000
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198103347732 [API loaded no]
[+30.469575ms] Reading GMA metadata...
[+30.531192ms] Preparing content folder...
[+30.556019ms] Creating new Workshop item...
[+184.306579ms] Preparing item 16592315458883944448 upload...
[+184.325874ms] Uploading item...
[+199.13136ms] Preparing config...

ERROR: Steam error (a file was not found)

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FastGmadError { kind: SteamError("a file was not found"), context: None }', fastgmad-bin/src/main.rs:87:31
stack backtrace:
   0:     0x5594f583d576 - <unknown>
   1:     0x5594f57cc81f - <unknown>
   2:     0x5594f583a737 - <unknown>
   3:     0x5594f583d385 - <unknown>
   4:     0x5594f583e823 - <unknown>
   5:     0x5594f583e5e4 - <unknown>
   6:     0x5594f583ed16 - <unknown>
   7:     0x5594f583ec24 - <unknown>
   8:     0x5594f583d976 - <unknown>
   9:     0x5594f583e9b2 - <unknown>
  10:     0x5594f57bf343 - <unknown>
  11:     0x5594f57bf783 - <unknown>
  12:     0x5594f5806a95 - <unknown>
  13:     0x5594f57ec523 - <unknown>
  14:     0x5594f57ed899 - <unknown>
  15:     0x5594f5833fc5 - <unknown>
  16:     0x5594f5809195 - <unknown>
  17:     0x7f0334627cd0 - <unknown>
  18:     0x7f0334627d8a - __libc_start_main
  19:     0x5594f57c522e - <unknown>
  20:                0x0 - <unknown>
Aborted (core dumped)
```

Seems like it gets something wrong at 'preparing config'.

For reference, I use this command to pack a folder to a .gma: `fastgmad create -folder "addons/auto_flashlight" -out auto_flashlight.gma`

The folder is structured like this, which I believe shouldn't cause any issues:
`addons/auto_flashlight/lua/autorun/...`
`addons/auto_flashlight/addon.json`
The addon only contains 1 Lua file and the addon.json:
```json
{
    "title": "Auto-Flashlight",
    "type": "effects",
    "tags": ["scenic", "roleplay"],
    "ignore": []
}
```

Also, I'm able to use `fastgmad update` to update the addon without any errors being printed in fastgmad, however this doesn't seem to actually fix the addon as attempting to download the workshop addon via gmpublisher results in an error, and the displayed file size on the page still says `0.000 MB`.

OS: `EndeavourOS Linux x86_64 (kernel 6.1.52-1-lts)`
Shell (not sure if this matters but I'll put it here anyway): `bash 5.1.16`
fastgmad version: `0.1.1`

**Comment by chev2** [comment]
Also, just as a sanity check, I checked to see if gmod's `bin/linux64/gmpublish` works, and it publishes the addon with no issues. gmpublisher is also able to download it fine.

**Comment by WilliamVenner** [comment]
Damn that sucks, I'm guessing that Steamworks doesn't understand symlinks on Unix. Works fine on Windows. I'll have to disable that for Unix builds

**Comment by WilliamVenner** [comment]
Give v0.1.2 a try

**Comment by chev2** [comment]
The same issue occurs. I don't believe symlinks were the culprit anyway; I'm creating and publishing the .gma from a local git repo, and I _do_ symlink the relevant addon folder in that repo into the GarrysMod addons/ folder, though I don't believe that should be affecting anything--I also use the original path, not the symlink, for gmpublish.

If you want to test the exact same addon I've been trying for reproducibility, you can find it here on GitHub: [chev2/gmod-addons](https://github.com/chev2/gmod-addons)

```
┌─[cpcl][endeavour-pc][±][main ?:1 ✗][~/Git/chev2/gmod-addons]
└─▪ >> fastgmad create -folder addons/auto_flashlight -out auto_flashlight.gma
fastgmad v0.1.2 by Billy
https://github.com/WilliamVenner/fastgmad
Prefer to use a GUI? Check out https://github.com/WilliamVenner/gmpublisher

[+148.984µs] Opening output file...
[+226.004µs] Reading addon.json...
[+261.76µs] Discovering entries...
[+354.982µs] Writing GMA metadata...
[+367.702µs] Writing file list...
[+378.625µs] Writing file contents...
[+689.227µs] Finished 

┌─[cpcl][endeavour-pc][±][main ?:2 ✗][~/Git/chev2/gmod-addons]
└─▪ >> fastgmad publish -addon auto_flashlight.gma -icon images/icon_auto_flashlight.png
fastgmad v0.1.2 by Billy
https://github.com/WilliamVenner/fastgmad
Prefer to use a GUI? Check out https://github.com/WilliamVenner/gmpublisher

[+53.069µs] Checking icon...
[+121.41µs] Initializing Steam...
[S_API] SteamAPI_Init(): Loaded '/home/cpcl/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 4000
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198103347732 [API loaded no]
[+63.735362ms] Reading GMA metadata...
[+63.803996ms] Preparing content folder...
[+63.854745ms] Creating new Workshop item...
[+218.859881ms] Preparing item 15875838497853014016 upload...
[+218.874275ms] Uploading item...
[+234.200464ms] Preparing config...

ERROR: Steam error (a file was not found)

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FastGmadError { kind: SteamError("a file was not found"), context: None }', fastgmad-bin/src/main.rs:89:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

**Comment by WilliamVenner** [comment]
Fixed in next update
